#!/usr/bin/env python3
"""Generate the whole site from src/apps.json.

    python3 src/build.py        # run from the repo root

Writes, at the repo root:
    app-ads.txt              one file, every app, every ad network
    index.html               hub listing the apps
    assets/site.css          the one stylesheet every page uses
    <slug>/index.html        landing page   (only if the app has a "landing" block)
    <slug>/privacy/index.html   privacy policy, Korean + English

Why generated rather than hand-written
--------------------------------------
Google Play rejects a privacy policy that does not identify the app and the
developer exactly as the store listing does. With ~10 apps that is ~20 pages of
near-identical text, and hand-editing them is how the identifiers drift apart —
which is exactly the rejection PaintBoard hit in August 2026 (a single shared
policy page that named no app at all). Here the identifiers live in one place,
`src/apps.json`, and every page is rebuilt from them.

Adding an app: add an entry to src/apps.json, drop its screenshots in
<slug>/assets/, run this script, commit. Then point that app's store listing
privacy-policy URL at https://huhphilgoo.github.io/<slug>/privacy/.
"""
import html
import json
import pathlib
import shutil

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / 'src' / 'apps.json').read_text(encoding='utf-8'))

DEV = DATA['developer']
SITE = DATA['site']

# Third-party SDK disclosures, keyed by the ids used in apps.json "services".
SERVICES = {
    'admob': {
        'name': 'Google AdMob',
        'ko': ('광고 게재',
               '광고 식별자(AAID/IDFA), 기기 정보(모델·운영체제 버전·언어·국가), '
               'IP 주소 기반의 대략적인 위치, 광고 상호작용 기록',
               '광고 게재, 광고 성과 측정, 광고 사기 방지, 이용자가 동의한 경우 맞춤 광고 제공'),
        'en': ('advertising',
               'advertising identifier (AAID/IDFA), device information (model, OS version, '
               'language, country), approximate location derived from IP address, and ad '
               'interaction data',
               'to serve and measure ads, prevent ad fraud, and — where you have consented — '
               'to personalize ads'),
        'url': 'https://policies.google.com/technologies/ads',
    },
    'firebaseAnalytics': {
        'name': 'Google Firebase Analytics',
        'ko': ('이용 통계',
               '앱 실행 및 사용 이벤트, 기기 및 앱 버전 정보, 대략적인 지역 정보, 앱 인스턴스 ID',
               '앱 안정성 확인 및 기능 개선을 위한 통계 분석'),
        'en': ('usage analytics',
               'app launch and usage events, device and app version information, approximate '
               'region, and app instance ID',
               'for stability monitoring and product improvement'),
        'url': 'https://firebase.google.com/support/privacy',
    },
}

E = html.escape


def page(title, body, css_depth, favicon='📱', description='', lang='en', head_extra=''):
    """Wrap body content in a full document. css_depth = how many ../ to reach the root."""
    up = '../' * css_depth
    desc = f'\n<meta name="description" content="{E(description)}">' if description else ''
    return f"""<!doctype html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{E(title)}</title>{desc}{head_extra}
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>{favicon}</text></svg>">
<link rel="stylesheet" href="{up}assets/site.css">
</head>
<body>
{body}
</body>
</html>
"""


# ── stylesheet ────────────────────────────────────────────────────────────────

CSS = """/* Generated by src/build.py — edit the template there, not this file. */
:root{
  --ground:#F1F2F4; --sheet:#FFFFFF; --ink:#14161A; --muted:#5B6371;
  --line:#DCDEE3; --line-soft:#EAEBEF; --accent:#ED1C24; --accent-ink:#FFFFFF;
  --shadow:0 1px 2px rgba(20,22,26,.06), 0 12px 32px -12px rgba(20,22,26,.18);
  --display:ui-rounded,"SF Pro Rounded","Hiragino Maru Gothic ProN","Apple SD Gothic Neo",system-ui,sans-serif;
  --body:system-ui,-apple-system,"Helvetica Neue","Apple SD Gothic Neo",sans-serif;
  --util:ui-monospace,"SF Mono",Menlo,Consolas,monospace;
}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){
  --ground:#0E1013; --sheet:#171A1F; --ink:#ECEEF2; --muted:#98A0AE;
  --line:#282C34; --line-soft:#20242A; --accent:#FF4A44; --accent-ink:#14161A;
  --shadow:0 1px 2px rgba(0,0,0,.5), 0 16px 40px -16px rgba(0,0,0,.7);
}}
:root[data-theme="dark"]{
  --ground:#0E1013; --sheet:#171A1F; --ink:#ECEEF2; --muted:#98A0AE;
  --line:#282C34; --line-soft:#20242A; --accent:#FF4A44; --accent-ink:#14161A;
  --shadow:0 1px 2px rgba(0,0,0,.5), 0 16px 40px -16px rgba(0,0,0,.7);
}
*{box-sizing:border-box}
body{margin:0;background:var(--ground);color:var(--ink);font-family:var(--body);
  font-size:17px;line-height:1.6;-webkit-font-smoothing:antialiased}
.wrap{max-width:1080px;margin:0 auto;padding:0 28px}
.narrow{max-width:760px}
section{padding:72px 0;border-top:1px solid var(--line-soft)}
section:first-of-type{border-top:0}
h1,h2,h3{font-family:var(--display);text-wrap:balance;margin:0}
h1{font-size:clamp(2.4rem,6vw,4.2rem);line-height:1.03;letter-spacing:-.03em;font-weight:800}
h2{font-size:clamp(1.5rem,3vw,2rem);line-height:1.16;letter-spacing:-.02em;font-weight:700}
h3{font-size:1.05rem;letter-spacing:-.01em;font-weight:700}
p{margin:0}
a{color:inherit}
.eyebrow{font-family:var(--util);font-size:.7rem;letter-spacing:.16em;
  text-transform:uppercase;color:var(--muted);margin-bottom:18px}
.lede{font-size:1.16rem;color:var(--muted);max-width:62ch}

/* masthead + footer, shared by every page */
.masthead{display:flex;align-items:center;gap:14px;padding:26px 0 0;flex-wrap:wrap}
.masthead a{text-decoration:none;font-family:var(--display);font-weight:700;
  letter-spacing:-.02em;font-size:1.02rem}
.masthead .spacer{flex:1}
.masthead .meta{font-family:var(--util);font-size:.72rem;letter-spacing:.1em;
  text-transform:uppercase;color:var(--muted)}
footer{padding:34px 0 56px;color:var(--muted);font-size:.86rem;display:flex;
  flex-wrap:wrap;gap:8px 22px;align-items:center;border-top:1px solid var(--line-soft)}
footer a{color:var(--muted);text-decoration:none;border-bottom:1px solid var(--line)}
footer a:hover{color:var(--ink)}
footer .spacer{flex:1}

/* hub */
.apps{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:18px;margin-top:36px}
.app{background:var(--sheet);border:1px solid var(--line);border-radius:14px;padding:24px;
  display:flex;flex-direction:column;gap:10px}
.app h3{display:flex;align-items:baseline;gap:9px}
.app .ko{font-family:var(--body);font-size:.85rem;font-weight:400;color:var(--muted)}
.app p{font-size:.93rem;color:var(--muted);flex:1}
.app .row{display:flex;flex-wrap:wrap;gap:8px 16px;font-size:.85rem}
.app .row a{text-decoration:none;border-bottom:1px solid var(--line);padding-bottom:1px}
.app .row a:hover{border-color:var(--accent)}

/* landing */
.hero{padding-top:52px}
.hero h1{margin-bottom:22px}
.markword{position:relative;display:inline-block;white-space:nowrap}
.markword svg{position:absolute;left:0;right:0;bottom:-.22em;width:100%;height:.34em;overflow:visible}
.markword path{fill:none;stroke:var(--accent);stroke-width:9;stroke-linecap:round;
  stroke-dasharray:340;stroke-dashoffset:340;animation:draw 1.05s cubic-bezier(.6,.05,.3,1) .35s forwards}
@keyframes draw{to{stroke-dashoffset:0}}
@media (prefers-reduced-motion:reduce){.markword path{animation:none;stroke-dashoffset:0}}
.cta{display:flex;flex-wrap:wrap;gap:12px;margin-top:30px}
.btn{display:inline-flex;align-items:center;gap:9px;padding:12px 20px;border-radius:11px;
  text-decoration:none;font-weight:600;font-size:.95rem;border:1px solid transparent;
  transition:transform .14s ease, box-shadow .14s ease}
.btn-primary{background:var(--accent);color:var(--accent-ink)}
.btn-secondary{background:var(--sheet);color:var(--ink);border-color:var(--line)}
.btn:hover{transform:translateY(-1px);box-shadow:var(--shadow)}
.btn:focus-visible{outline:2px solid var(--accent);outline-offset:3px}
.btn svg{width:17px;height:17px;flex:none}
.shot{margin:52px 0 0;background:var(--sheet);border:1px solid var(--line);
  border-radius:16px;padding:12px;box-shadow:var(--shadow)}
.shot img{width:100%;display:block;border-radius:8px}
.caption{font-family:var(--util);font-size:.72rem;letter-spacing:.08em;
  text-transform:uppercase;color:var(--muted);margin-top:14px}
.two{display:grid;grid-template-columns:1fr 1fr;gap:26px;margin-top:34px}
.card{background:var(--sheet);border:1px solid var(--line);border-radius:14px;padding:26px}
.card h3{margin-bottom:16px}
.list{list-style:none;padding:0;margin:0;display:flex;flex-direction:column;gap:11px;font-size:.97rem}
.list li{display:flex;gap:10px;align-items:baseline}
.tick{font-family:var(--util);color:var(--accent);flex:none;font-size:.9rem}
.cross{font-family:var(--util);color:var(--muted);flex:none;font-size:.9rem}
.gone{color:var(--muted);text-decoration:line-through;text-decoration-color:var(--line)}
.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--line-soft);
  border:1px solid var(--line-soft);border-radius:14px;overflow:hidden;margin-top:34px}
.cell{background:var(--sheet);padding:24px}
.cell h3{margin-bottom:7px}
.cell p{font-size:.92rem;color:var(--muted)}
.swatches{display:grid;grid-template-columns:repeat(18,1fr);gap:6px;margin-top:32px}
.sw{aspect-ratio:1;border-radius:7px;border:1px solid rgba(120,120,120,.28);position:relative;transition:transform .16s ease}
.sw:hover{transform:translateY(-5px) scale(1.06);z-index:2}
.sw::after{content:attr(data-hex);position:absolute;left:50%;top:-26px;transform:translateX(-50%);
  font-family:var(--util);font-size:.62rem;color:var(--muted);background:var(--sheet);
  border:1px solid var(--line);border-radius:5px;padding:2px 6px;opacity:0;
  pointer-events:none;transition:opacity .16s ease;white-space:nowrap}
.sw:hover::after{opacity:1}
.story{display:grid;grid-template-columns:1fr 1fr;gap:44px;align-items:start;margin-top:30px}
.story p{color:var(--muted)}
.story p+p{margin-top:16px}
.story strong{color:var(--ink);font-weight:600}
.rule{display:flex;gap:14px;align-items:baseline;padding:14px 0;border-bottom:1px solid var(--line-soft)}
.rule:last-child{border-bottom:0}
.year{font-family:var(--util);font-size:.78rem;color:var(--accent);letter-spacing:.06em;flex:none;width:44px}
.rule span:last-child{font-size:.95rem;color:var(--muted)}

/* policy */
.policy h2{margin:44px 0 14px}
.policy h2:first-of-type{margin-top:32px}
.policy p{margin:0 0 14px;color:var(--muted)}
.policy ul{margin:0 0 14px;padding-left:1.15rem;color:var(--muted)}
.policy li{margin-bottom:7px}
.policy strong{color:var(--ink);font-weight:600}
.policy a{color:var(--ink)}
.idblock{background:var(--sheet);border:1px solid var(--line);border-radius:14px;
  padding:22px 24px;margin:26px 0 34px}
.idblock dl{margin:0;display:grid;grid-template-columns:auto 1fr;gap:9px 20px;font-size:.95rem}
.idblock dt{color:var(--muted);font-family:var(--util);font-size:.76rem;
  letter-spacing:.08em;text-transform:uppercase;padding-top:3px}
.idblock dd{margin:0;font-weight:600}
.tablewrap{overflow-x:auto;margin:0 0 14px}
table{border-collapse:collapse;width:100%;font-size:.93rem;min-width:32rem}
th,td{text-align:left;padding:11px 14px;border-bottom:1px solid var(--line-soft);vertical-align:top}
th{font-family:var(--util);font-size:.72rem;letter-spacing:.08em;text-transform:uppercase;
  color:var(--muted);font-weight:400}
td{color:var(--muted)}
td:first-child{color:var(--ink);font-weight:600;white-space:nowrap}
.langswitch{display:flex;gap:8px;margin-top:26px}
.langswitch a{font-family:var(--util);font-size:.74rem;letter-spacing:.08em;text-transform:uppercase;
  text-decoration:none;color:var(--muted);border:1px solid var(--line);border-radius:8px;padding:6px 12px}
.langswitch a:hover{color:var(--ink);border-color:var(--accent)}

/* EN / KO switcher in the masthead */
.langnav{display:flex;border:1px solid var(--line);border-radius:9px;overflow:hidden;background:var(--sheet)}
.langnav a{font-family:var(--util);font-size:.72rem;letter-spacing:.09em;text-decoration:none;
  color:var(--muted);padding:5px 11px;line-height:1.5}
.langnav a+a{border-left:1px solid var(--line)}
.langnav a:hover{color:var(--ink)}
.langnav a.on{background:var(--accent);color:var(--accent-ink)}
.langnav a:focus-visible{outline:2px solid var(--accent);outline-offset:2px}

@media (max-width:860px){
  .two,.story{grid-template-columns:1fr}
  .grid{grid-template-columns:repeat(2,1fr)}
  .swatches{grid-template-columns:repeat(9,1fr)}
  section{padding:56px 0}
}
@media (max-width:520px){
  .grid{grid-template-columns:1fr}
  body{font-size:16px}
  .idblock dl{grid-template-columns:1fr;gap:3px 0}
  .idblock dd{margin-bottom:10px}
}
"""


def langnav(current, hrefs):
    """EN / KO switcher. `hrefs` maps a lang code to its URL relative to the current page."""
    out = []
    for code, label in (('en', 'EN'), ('ko', 'KO')):
        cls = ' class="on"' if code == current else ''
        out.append(f'<a href="{E(hrefs[code])}" hreflang="{code}"{cls}>{label}</a>')
    return f'<nav class="langnav" aria-label="Language">{"".join(out)}</nav>'


def masthead(depth, right='', nav=''):
    """No wordmark: the owner's handle is deliberately kept off the pages."""
    return (f'<div class="masthead"><span class="spacer"></span>'
            f'{nav}<span class="meta">{right}</span></div>')


def footer(depth, app=None, lang='en'):
    """No package id and no developer name here — both were removed at the owner's
    request. They still appear in the identifier block of each privacy policy, where
    Google requires them; do not strip them from there."""
    up = '../' * depth
    left = f'{E(app["name"])} ({E(app["nameKo"])})' if app else ''
    label = {'en': ('Privacy policy', 'Contact'), 'ko': ('개인정보처리방침', '문의')}[lang]
    privacy = f'<a href="{up}{app["slug"]}/privacy/">{label[0]}</a>' if app else ''
    return (f'<footer><span>{left}</span><span class="spacer"></span>{privacy}'
            f'<a href="mailto:{E(DEV["email"])}">{label[1]}</a></footer>')


STORE_ICONS = {
    'play': '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M3.6 2.2 13 11.6l-9.4 9.4a1.6 1.6 0 0 1-.5-1.2V3.4c0-.5.2-.9.5-1.2Zm11 7.8L5.9 1.4l9.6 5.5 2 1.2-2.9 1.9Zm2.9 4.1-2-1.2-1.6 1.1 2.6 2.6 3.4-2c.9-.5.9-1.7 0-2.2l-3.4-2-.6.4 1.6 1.1c.9.5.9 1.7 0 2.2ZM5.9 22.6l8.7-8.7 2.9 1.9-11.6 6.8Z"/></svg>',
    'appStore': '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M16.4 12.7c0-2.3 1.9-3.4 2-3.5-1.1-1.6-2.8-1.8-3.4-1.8-1.4-.1-2.8.9-3.5.9-.7 0-1.8-.8-3-.8-1.5 0-2.9.9-3.7 2.3-1.6 2.7-.4 6.8 1.1 9 .8 1.1 1.6 2.3 2.8 2.2 1.1 0 1.6-.7 2.9-.7 1.3 0 1.7.7 2.9.7 1.2 0 2-1.1 2.7-2.2.9-1.2 1.2-2.5 1.2-2.5 0 0-2.3-.9-2.3-3.6ZM14.2 5.4c.6-.8 1-1.9.9-3-.9 0-2 .6-2.7 1.4-.6.7-1.1 1.8-.9 2.9 1 .1 2.1-.5 2.7-1.3Z"/></svg>',
}
STORE_LABELS = {'play': 'Google Play', 'appStore': 'App Store'}


def store_buttons(app):
    out = []
    for i, key in enumerate(('play', 'appStore')):
        url = app['links'].get(key)
        if not url:
            continue
        cls = 'btn-primary' if i == 0 else 'btn-secondary'
        out.append(f'<a class="btn {cls}" href="{E(url)}">{STORE_ICONS[key]}{STORE_LABELS[key]}</a>')
    return f'<div class="cta">{"".join(out)}</div>'


# ── privacy page ──────────────────────────────────────────────────────────────

def privacy_page(app, lang):
    """One locale per URL: English at /<slug>/privacy/, Korean at /<slug>/privacy/ko/.

    The identifier block stays on BOTH pages. Google rejected this app's earlier policy
    precisely because it did not name the app and developer as the store listing does,
    so the block is not optional decoration — do not remove it to tidy the page up.
    """
    p = app['privacy']
    # iOS-only apps have no Play listing; fall back to the Korean App Store name
    store_ko = (app['storeNames'].get('play') or app['storeNames'].get('appStoreKo')
                or app['name'])
    dev_ko, dev_en = DEV['nameKo'], DEV['nameEn']
    upd = app['policyUpdated']

    idblock = f"""<div class="idblock"><dl>
<dt>앱 이름 / App</dt><dd>{E(app['nameKo'])} ({E(app['name'])})</dd>
<dt>개발자 / Developer</dt><dd>{E(dev_ko)} ({E(dev_en)})</dd>
<dt>패키지명 / Package</dt><dd>{E(app['package'])}</dd>
<dt>문의 / Contact</dt><dd><a href="mailto:{E(DEV['email'])}">{E(DEV['email'])}</a></dd>
</dl></div>"""

    # Korean
    ko = [f'<p>본 개인정보처리방침은 <strong>{E(dev_ko)}</strong>(이하 "개발자")가 개발·게시한 애플리케이션 '
          f'<strong>{E(store_ko)}</strong>(패키지명 <code>{E(app["package"])}</code>, 이하 "본 앱")에 적용됩니다. '
          f'최종 수정일: {E(upd["ko"])}.</p>']
    ko.append('<h2>1. 개발자가 직접 수집하는 정보</h2>')
    ko.append('<p>개발자는 본 앱을 통해 이용자의 개인정보를 <strong>직접 수집하거나 서버에 저장하지 않습니다.</strong> '
              '본 앱은 회원가입, 로그인, 계정 생성을 요구하지 않습니다.</p>')
    ko.append(f'<p>{E(p["storage"]["ko"])}</p>')

    ko.append('<h2>2. 제3자 서비스가 자동으로 수집하는 정보</h2>')
    for sid in p['services']:
        s = SERVICES[sid]
        purpose, collected, why = s['ko']
        ko.append(f'<p><strong>{E(s["name"])} — {E(purpose)}</strong></p><ul>'
                  f'<li>수집 항목: {E(collected)}</li>'
                  f'<li>이용 목적: {E(why)}</li>'
                  f'<li>처리 주체: Google LLC · <a href="{s["url"]}">{s["url"]}</a></li></ul>')
    consent = []
    if p['consent'].get('ump'):
        consent.append('유럽경제지역(EEA)·영국 등 해당 지역 이용자에게는 앱 최초 실행 시 '
                       '<strong>Google UMP(사용자 메시지 플랫폼)</strong>를 통해 광고 개인 맞춤설정 동의 여부를 확인합니다.')
    if p['consent'].get('att'):
        consent.append('iOS에서는 <strong>앱 추적 투명성(ATT)</strong> 권한 요청을 통해 이용자가 추적을 허용하거나 거부할 수 있습니다.')
    if consent:
        ko.append('<p><strong>동의 관리</strong></p><ul>' + ''.join(f'<li>{c}</li>' for c in consent) + '</ul>')

    rows = ''.join(f'<tr><td>{E(x["ko"][0])}</td><td>{E(x["ko"][1])}</td><td>{E(x["ko"][2])}</td></tr>'
                   for x in p['permissions'])
    ko.append('<h2>3. 기기 권한 사용</h2><div class="tablewrap"><table>'
              '<tr><th>권한</th><th>사용 목적</th><th>비고</th></tr>' + rows + '</table></div>')

    ko.append('<h2>4. 정보의 제3자 제공</h2><p>개발자는 이용자의 개인정보를 제3자에게 판매하거나 대여하지 않습니다. '
              '위 2항에 기재된 제3자 서비스(Google LLC)가 각자의 정책에 따라 정보를 처리하는 경우를 제외하고는 '
              '어떠한 정보도 공유하지 않습니다.</p>')
    ko.append('<h2>5. 데이터 보관 및 삭제</h2><ul>'
              '<li>이용자가 앱에서 만든 데이터와 설정값은 기기 내부에만 저장되며, <strong>앱을 삭제하면 함께 삭제</strong>됩니다.</li>'
              '<li>광고 식별자의 재설정 및 삭제는 기기 설정에서 하실 수 있습니다. '
              'Android: 설정 → Google → 광고 / iOS: 설정 → 개인정보 보호 및 보안 → 추적</li>'
              f'<li>제3자 서비스에 수집된 정보의 삭제를 원하시는 경우 <a href="mailto:{E(DEV["email"])}">{E(DEV["email"])}</a>로 연락해 주시면 안내해 드립니다.</li></ul>')
    ko.append(f'<h2>6. 아동의 개인정보</h2><p>본 앱은 만 {p["minAge"]}세 미만 아동을 대상으로 하지 않으며, '
              '아동으로부터 고의로 개인정보를 수집하지 않습니다.</p>')
    ko.append('<h2>7. 방침의 변경</h2><p>본 방침이 변경되는 경우 본 페이지에 변경 내용과 최종 수정일을 게시합니다.</p>')
    ko.append(f'<h2>8. 문의처</h2><p>개발자 {E(dev_ko)} · {E(store_ko)} (<code>{E(app["package"])}</code>) · '
              f'<a href="mailto:{E(DEV["email"])}">{E(DEV["email"])}</a></p>')

    # English
    store_en = app['storeNames'].get('appStore') or app['name']
    en = [f'<p>This Privacy Policy applies to the mobile application <strong>{E(app["name"])}</strong> '
          f'(listed as “{E(store_en)}”, package <code>{E(app["package"])}</code>), developed and published by '
          f'<strong>{E(dev_en)} ({E(dev_ko)})</strong>. Last updated: {E(upd["en"])}.</p>']
    en.append('<h2>1. Information collected directly by the developer</h2>'
              '<p>The developer does not collect or store any personal information on any server. '
              'The app requires no sign-up, login, or account.</p>')
    en.append(f'<p>{E(p["storage"]["en"])}</p>')
    en.append('<h2>2. Information collected by third-party services</h2>')
    for sid in p['services']:
        s = SERVICES[sid]
        purpose, collected, why = s['en']
        en.append(f'<p><strong>{E(s["name"])} ({E(purpose)})</strong>: {E(collected)} — used {E(why)}. '
                  f'Processed by Google LLC. <a href="{s["url"]}">{s["url"]}</a></p>')
    ce = []
    if p['consent'].get('ump'):
        ce.append('Users in the EEA and the UK are shown a Google UMP consent form on first launch.')
    if p['consent'].get('att'):
        ce.append('On iOS, App Tracking Transparency (ATT) lets you allow or deny tracking.')
    if ce:
        en.append('<p><strong>Consent.</strong> ' + ' '.join(ce) + '</p>')
    rows_en = ''.join(f'<tr><td>{E(x["en"][0])}</td><td>{E(x["en"][1])}</td><td>{E(x["en"][2])}</td></tr>'
                      for x in p['permissions'])
    en.append('<h2>3. Device permissions</h2><div class="tablewrap"><table>'
              '<tr><th>Permission</th><th>Purpose</th><th>Note</th></tr>' + rows_en + '</table></div>')
    en.append('<h2>4. Sharing of information</h2><p>The developer does not sell or rent your personal '
              'information. No information is shared other than the processing performed by the '
              'third-party services listed in section 2 (Google LLC) under their own policies.</p>')
    en.append('<h2>5. Retention and deletion</h2><p>Your data and settings are stored only on your device '
              'and are removed when you uninstall the app. You can reset or delete your advertising ID in '
              'your device settings (Android: Settings → Google → Ads; iOS: Settings → Privacy &amp; Security → '
              f'Tracking). For deletion requests concerning third-party data, contact '
              f'<a href="mailto:{E(DEV["email"])}">{E(DEV["email"])}</a>.</p>')
    en.append(f'<h2>6. Children’s privacy</h2><p>This app is not directed to children under the age of '
              f'{p["minAge"]}, and the developer does not knowingly collect personal information from them.</p>')
    en.append('<h2>7. Changes to this policy</h2><p>Any changes will be posted on this page with an '
              'updated revision date.</p>')
    en.append(f'<h2>8. Contact</h2><p>{E(dev_en)} ({E(dev_ko)}) · {E(app["name"])} '
              f'(<code>{E(app["package"])}</code>) · <a href="mailto:{E(DEV["email"])}">{E(DEV["email"])}</a></p>')

    depth = 2 if lang == 'en' else 3
    hrefs = ({'en': './', 'ko': 'ko/'} if lang == 'en' else {'en': '../', 'ko': './'})
    base, slug = SITE['baseUrl'], app['slug']
    alternates = ''.join(
        f'\n<link rel="alternate" hreflang="{c}" href="{base}/{slug}/privacy/{"" if c == "en" else "ko/"}">'
        for c in LANGS)

    if lang == 'ko':
        eyebrow, heading, sections = '개인정보처리방침', app['nameKo'], ko
        title = f'{app["nameKo"]} 개인정보처리방침'
        desc = f'{app["nameKo"]}({app["package"]}) 개인정보처리방침.'
    else:
        eyebrow, heading, sections = 'Privacy policy', app['name'], en
        title = f'{app["name"]} — Privacy policy'
        desc = f'Privacy policy for {app["name"]} ({app["nameKo"]}), {app["package"]}.'

    body = f"""<div class="wrap narrow">
{masthead(depth, E(app['name']), langnav(lang, hrefs))}
<section class="policy">
  <p class="eyebrow">{E(eyebrow)}</p>
  <h1>{E(heading)}</h1>
  {idblock}
  {''.join(sections)}
</section>
{footer(depth, app, lang)}
</div>"""
    return page(title, body, depth, '🔒', desc, lang=lang, head_extra=alternates)


# ── landing page ──────────────────────────────────────────────────────────────

LANGS = ('en', 'ko')


def landing_page(app, lang):
    """Render one locale of an app's landing page.

    English lives at /<slug>/ and Korean at /<slug>/ko/, so the Korean page sits one
    level deeper — every relative path below is derived from `depth` rather than
    hard-coded, which is the thing that breaks when a locale is added carelessly.
    """
    L = app['landing']
    T = L[lang]
    depth = 1 if lang == 'en' else 2
    up = '../' * (depth - 1)          # from this page back to the app's own directory
    base = SITE['baseUrl']
    slug = app['slug']

    head, mark = T['headline']
    shots = L.get('shots', [])

    def shot(i):
        if i >= len(shots):
            return ''
        s = shots[i]
        alt, cap = s[lang]
        return (f'<figure class="shot"><img src="{E(up + s["src"])}" alt="{E(alt)}" loading="lazy">'
                f'<figcaption class="caption">{E(cap)}</figcaption></figure>')

    left = ''.join(f'<li><span class="cross">—</span><span class="gone">{E(x)}</span></li>'
                   for x in T['leftOut'])
    keep = ''.join(f'<li><span class="tick">+</span><span>{E(x)}</span></li>'
                   for x in T['remains'])
    cells = ''.join(f'<div class="cell"><h3>{E(t)}</h3><p>{E(d)}</p></div>'
                    for t, d in T['features']['items'])
    sw = ''.join(f'<span class="sw" style="background:{c}" data-hex="{c}"></span>'
                 for c in L.get('palette', []))
    paras = ''.join(f'<p>{t}</p>' for t in T['story']['paragraphs'])
    rules = ''.join(f'<div class="rule"><span class="year">{E(y)}</span><span>{E(t)}</span></div>'
                    for y, t in T['story']['timeline'])

    palette_section = ''
    if sw:
        ps = T['paletteSection']
        palette_section = f"""<section>
  <p class="eyebrow">{E(ps['eyebrow'])}</p>
  <h2>{E(ps['title'])}</h2>
  <p class="lede" style="margin-top:14px">{ps['lede']}</p>
  <div class="swatches">{sw}</div>
  {shot(1)}
</section>"""

    # Apps without a palette have no home for shot(1); give it to the features section
    feature_shot = '' if sw else shot(1)

    sibling = (f'<p class="lede" style="margin-top:18px">{T["story"]["sibling"]}</p>'
               if T['story'].get('sibling') else '')

    privacy_href = f'{up}privacy/'
    privacy_lede = T['privacySection']['lede'].replace(
        '{privacy}', f'<a href="{privacy_href}">{E(T["privacyLinkText"])}</a>')

    # Cross-locale links, plus hreflang so search engines pair the two pages.
    hrefs = {'en': up or './', 'ko': f'{up}ko/'} if lang == 'en' else {'en': '../', 'ko': './'}
    alternates = ''.join(
        f'\n<link rel="alternate" hreflang="{c}" href="{base}/{slug}/{"" if c == "en" else "ko/"}">'
        for c in LANGS)

    idea, feat, story, priv, close = (T['idea'], T['features'], T['story'],
                                      T['privacySection'], T['close'])

    body = f"""<div class="wrap">
{masthead(depth, T['meta'], langnav(lang, hrefs))}

<section class="hero">
  <h1>{E(head)}
    <span class="markword">{E(mark)}<svg viewBox="0 0 340 24" aria-hidden="true"><path d="M4 16 C58 6, 96 20, 150 12 C204 4, 246 18, 336 9"/></svg></span>.
  </h1>
  <p class="lede">{T['lede']}</p>
  {store_buttons(app)}
  {shot(0)}
</section>

<section>
  <p class="eyebrow">{E(idea['eyebrow'])}</p>
  <h2>{E(idea['title'])}</h2>
  <p class="lede" style="margin-top:14px">{idea['lede']}</p>
  <div class="two">
    <div class="card"><h3>{E(T['leftOutTitle'])}</h3><ul class="list">{left}</ul></div>
    <div class="card"><h3>{E(T['remainsTitle'])}</h3><ul class="list">{keep}</ul></div>
  </div>
</section>

<section>
  <p class="eyebrow">{E(feat['eyebrow'])}</p>
  <h2>{E(feat['title'])}</h2>
  <div class="grid">{cells}</div>{feature_shot}
</section>

{palette_section}

<section>
  <p class="eyebrow">{E(story['eyebrow'])}</p>
  <h2>{E(story['title'])}</h2>
  <div class="story">
    <div>{paras}</div>
    <div>{rules}</div>
  </div>
  {sibling}
</section>

<section>
  <p class="eyebrow">{E(priv['eyebrow'])}</p>
  <h2>{E(priv['title'])}</h2>
  <p class="lede" style="margin-top:14px">{privacy_lede}</p>
</section>

<section>
  <h2>{E(close['title'])}</h2>
  <p class="lede" style="margin-top:12px">{close['lede']}</p>
  {store_buttons(app)}
  {shot(2)}
</section>

{footer(depth, app, lang)}
</div>"""

    summary = app['summary'] if lang == 'en' else app.get('summaryKo', app['summary'])
    return page(app['name'], body, depth, '🎨', summary, lang=lang, head_extra=alternates)


# ── hub ───────────────────────────────────────────────────────────────────────

def hub_page():
    cards = []
    for app in DATA['apps']:
        links = []
        if app.get('landing'):
            links.append(f'<a href="{E(app["slug"])}/">About</a>')
        for key in ('play', 'appStore'):
            if app['links'].get(key):
                links.append(f'<a href="{E(app["links"][key])}">{STORE_LABELS[key]}</a>')
        links.append(f'<a href="{E(app["slug"])}/privacy/">Privacy</a>')
        cards.append(f"""<div class="app">
  <h3>{E(app['name'])}<span class="ko">{E(app['nameKo'])}</span></h3>
  <p>{E(app['summary'])}</p>
  <div class="row">{''.join(links)}</div>
</div>""")

    body = f"""<div class="wrap">
{masthead(0)}
<section>
  <p class="eyebrow">Apps</p>
  <h1>{E(SITE['title'])}</h1>
  <p class="lede" style="margin-top:16px">{E(SITE['intro'])}</p>
  <div class="apps">{''.join(cards)}</div>
</section>
{footer(0)}
</div>"""
    return page(SITE['title'], body, 0, '📱', SITE['intro'])


# ── write everything ──────────────────────────────────────────────────────────

def main():
    lines = [f'{n["domain"]}, {n["publisherId"]}, {n["relationship"]}, {n["certId"]}'
             for n in DATA['adNetworks']]
    (ROOT / 'app-ads.txt').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print('app-ads.txt')

    (ROOT / 'assets').mkdir(exist_ok=True)
    (ROOT / 'assets' / 'site.css').write_text(CSS, encoding='utf-8')
    print('assets/site.css')

    (ROOT / 'index.html').write_text(hub_page(), encoding='utf-8')
    print('index.html')

    for app in DATA['apps']:
        d = ROOT / app['slug']
        for lang in LANGS:
            target = d / 'privacy' if lang == 'en' else d / 'privacy' / lang
            target.mkdir(parents=True, exist_ok=True)
            (target / 'index.html').write_text(privacy_page(app, lang), encoding='utf-8')
            print(f'{app["slug"]}/privacy/{"" if lang == "en" else lang + "/"}index.html')
        if app.get('landing'):
            for lang in LANGS:
                target = d if lang == 'en' else d / lang
                target.mkdir(parents=True, exist_ok=True)
                (target / 'index.html').write_text(landing_page(app, lang), encoding='utf-8')
                print(f'{app["slug"]}/{"" if lang == "en" else lang + "/"}index.html')

    (ROOT / '.nojekyll').touch()


if __name__ == '__main__':
    main()
